def ANSIBLE_CONFIG = """\
[defaults]
log_path = ./ansible.log
"""

pipeline {

  // agent any

  agent {
    docker {
      image 'ymktk/ansible:ansible-2.9.5-centos'
      args '-v $HOME/.m2:/root/.m2 -e PATH=$PATH:/home/ansible/.local/bin'
    }
  }

  stages() {

    stage('1. Greeting') {
      steps {
        echo 'Hello world'
      }
    }

    stage('2. check where I am') {
      steps() {
        echo "${hostname}"
        sh 'pwd'
        sh 'id'
        sh 'ls -l'
      }
    }

    //https://plugins.jenkins.io/ansible/
    stage('run playbook') {
      steps {
        echo "${hostname}"
        ansiblePlaybook(
          playbook:  '02-ansible/ansible-deploy/tests/test.yml',
          inventory: '02-ansible/ansible-deploy/tests/inventory.yml',
          colorized: true
        )
      }

      post {
        always {
          archiveArtifacts 'ansible.log'
        }
      }
    }


  } // End Stages

  post {
    success {
      cleanWs()
    }
  }

}
